### ISSUE TITLE
Crash Android 5.1.1

### ISSUE THREAD

**Issue by sijad** [getlantern/lantern-mobile#16]
application will close without any message or error after i open application and then click on start button
here is [logcat](https://gist.github.com/sijad/f8e0a7ac47618b0e1c30)
as it's a custom rom so I'm not sure if this problem is just because of my rom but i can confirm other vpn apps like openvpn, shadowsocks and psyphon, etc works well

**Comment by atavism** [comment]
Thanks, @sijad. Where did you download the version you tested from? We haven't released a version publicly yet, but we're planning to send out a prototype to an initial group of test users. Do you want to send an e-mail to team@getlantern.org and I'll make sure you're added?

**Comment by sijad** [comment]
i just test and build [inital-release](https://github.com/getlantern/lantern-mobile/tree/initial-release) with Android Studio.
