### ISSUE TITLE
Custom share screen

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern-mobile#17]
I finally figured out how to limit/filter the apps we present in the share intent:

![image](https://cloud.githubusercontent.com/assets/6346213/10357008/1de5f5ee-6d32-11e5-9059-88722eee3f21.png)

We can also use custom messages for each

**Comment by myleshorton** [comment]
Awesome!!

On Wed, Oct 7, 2015 at 2:53 PM, atavism notifications@github.com wrote:

> I finally figured out how to limit/filter the apps we present in the share
> intent:
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/6346213/10352284/154e2a02-6d03-11e5-955e-ddb2d53a9de5.png
> 
> We can also use custom messages for each
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/getlantern/lantern-mobile/issues/17.

## 

## 

President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by Derekf5** [comment]
Awesome! Yeah I thought the share intent might be hard to alter, but this doesn't look to different from the overall app so I think it is ok.  Thanks @atavism!
