### ISSUE TITLE
Privacy policy link doesn't do anything

### ISSUE THREAD

**Issue by myleshorton** [getlantern/lantern-mobile#21]
Not actually sure it should be there at all, but it currently doesn't go anywhere

**Comment by Derekf5** [comment]
@myleshorton should we just make a link to our FAQ instead? or delete that option all together?

**Comment by myleshorton** [comment]
I would probably just take it out. I don't really think it's worth cluttering up the screen with it. If we include it at all, it should definitely go somewhere, and I believe the only online privacy policy we have is on the wiki in GitHub.

**Comment by atavism** [comment]
Thanks, @myleshorton. I removed it!
