### ISSUE TITLE
Back arrow on "desktop version" screen opens menu

### ISSUE THREAD

**Issue by Derekf5** [getlantern/lantern-mobile#25]
as opposed to leading the user back to the previous page it opens the menu.

**Comment by atavism** [comment]
That back arrow would always go back to the main screen then? since no other previous page is possible. It seemed more natural to me presenting the side-menu again; for instance, if the user wants to select the Share or Contact option directly from that screen.

**Comment by Derekf5** [comment]
Yes I think the back arrow should go back to the main screen. i looked into several other apps that have similar situations, and it seems to be fairly standard for that to return to the main screen.   For instance in google maps if you click on the menu, then go to settings it takes you to a separate page. the back arrow then returns you to the main map.

**Comment by atavism** [comment]
Ok, cool! I'll fix it

**Comment by Derekf5** [comment]
Thanks!
