### ISSUE TITLE
Add status bar icon while Lantern is running

### ISSUE THREAD

**Issue by atavism** [getlantern/lantern-mobile#38]
![image](https://cloud.githubusercontent.com/assets/6346213/11226426/a7ab2c1e-8d34-11e5-8517-e6eded47faa1.png)

Whenever Lantern is running/the VPN connection is active, an icon should appear in the status bar.

**Comment by sunshine19090** [comment]
Closing this as we now have a key sign to show the status.

**Comment by sunshine19090** [comment]
Oh! I don't have permission to close this. Can you please do it @atavism ?

**Comment by atavism** [comment]
Sure, @sunshine19090. Also gave you admin access so you should be able to close tickets again
