### ISSUE TITLE
Language in UI is not changed for Desktop version side menu, the switch as well as the message when the switch is flipped

### ISSUE THREAD

**Issue by sunshine19090** [getlantern/lantern-mobile#47]
When I changed the language other than English, the language in Lantern UI for Desktop version didn't change. Also, the messages when the switched is turned ON/OFF is also displayed in English.

**Comment by myleshorton** [comment]
I think we should actually have this in the lantern tickets @sunshine19090 so we can keep track of things by version.

**Comment by sunshine19090** [comment]
Sure @myleshorton. Do you want me to move it to 2.1.1 or are we going to fix it in 2.1.0?

**Comment by myleshorton** [comment]
I would put it in 2.1.0

On Tue, Mar 8, 2016 at 12:51 PM, sunshine19090 notifications@github.com
wrote:

> Sure @myleshorton https://github.com/myleshorton. Do you want me to
> move it to 2.1.1 or are we going to fix it in 2.1.0?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/getlantern/lantern-mobile/issues/47#issuecomment-193961064
> .

## 

## 

President
Brave New Software Project, Inc.
https://www.getlantern.org
pgp A998 2B6E EF1C 373E 723F A813 045D A255 901A FD89

**Comment by sunshine19090** [comment]
Done!
